PUT http://localhost:8080/events/6
content-type: application/json

{
  "name": "Updated event",
  "description": "A test event",
  "location": "Test Location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
