// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/auth.proto

package grpc_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequestPayload) Reset() {
	*x = AuthRequestPayload{}
	mi := &file_protos_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequestPayload) ProtoMessage() {}

func (x *AuthRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequestPayload.ProtoReflect.Descriptor instead.
func (*AuthRequestPayload) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequestPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequestPayload) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponsePayload) Reset() {
	*x = AuthResponsePayload{}
	mi := &file_protos_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponsePayload) ProtoMessage() {}

func (x *AuthResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponsePayload.ProtoReflect.Descriptor instead.
func (*AuthResponsePayload) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponsePayload) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *AuthResponsePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponsePayload) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_protos_auth_proto protoreflect.FileDescriptor

const file_protos_auth_proto_rawDesc = "" +
	"\n" +
	"\x11protos/auth.proto\x12\vgrpc_server\"F\n" +
	"\x12AuthRequestPayload\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\x13AuthResponsePayload\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2`\n" +
	"\vAuthService\x12Q\n" +
	"\fAuthenticate\x12\x1f.grpc_server.AuthRequestPayload\x1a .grpc_server.AuthResponsePayloadB\x16Z\x14internal/grpc_serverb\x06proto3"

var (
	file_protos_auth_proto_rawDescOnce sync.Once
	file_protos_auth_proto_rawDescData []byte
)

func file_protos_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)))
	})
	return file_protos_auth_proto_rawDescData
}

var file_protos_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_auth_proto_goTypes = []any{
	(*AuthRequestPayload)(nil),  // 0: grpc_server.AuthRequestPayload
	(*AuthResponsePayload)(nil), // 1: grpc_server.AuthResponsePayload
}
var file_protos_auth_proto_depIdxs = []int32{
	0, // 0: grpc_server.AuthService.Authenticate:input_type -> grpc_server.AuthRequestPayload
	1, // 1: grpc_server.AuthService.Authenticate:output_type -> grpc_server.AuthResponsePayload
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_auth_proto_init() }
func file_protos_auth_proto_init() {
	if File_protos_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_proto = out.File
	file_protos_auth_proto_goTypes = nil
	file_protos_auth_proto_depIdxs = nil
}
