# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    node1.vm.box = "generic/ubuntu1804"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # node1.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # node1.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # node1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # node1.vm.network "private_network", ip: "192.168.33.10"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    node1.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    node1.vm.synced_folder "./scripts", "/vagrant/scripts"

    # Disable the default share of the current code directory. Doing this
    # provides improved isolation between the vagrant box and your host
    # by making sure your Vagrantfile isn't accessible to the vagrant box.
    # If you use this you may want to enable additional shared subfolders as
    # shown above.
    node1.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__args: ["-r", "--include=swarm.yml", "--exclude=*"]

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    node1.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true

      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end
    #
    # View the documentation for the provider you are using for more
    # information on available options.

    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    node1.vm.provision "shell", inline: <<-SHELL
      export VERSION_CODENAME=$(env -i bash -c '. /etc/os-release; echo $VERSION_CODENAME')
      export IP_ADDR=$(ip addr show eth1 | grep 'inet ' | awk '{print $2}' | cut -f1 -d'/')
      sudo sh -c "echo 'export IP_ADDR=${IP_ADDR}' > /etc/profile.d/ip_addr.sh"
      sudo apt-get install ufw ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      sudo apt-get update
      sudo apt-get install docker.io -y

      cd /vagrant
      sudo hostnamectl set-hostname node1

      # Edit configs
      sudo sed -i "s/localhost/${IP_ADDR}/g" ./scripts/Caddyfile
      sudo sed -i "s/localhost/${IP_ADDR}/g" ./swarm.yml

      # Firewall
      sudo ufw allow ssh
      sudo ufw allow http
      sudo ufw allow https
      sudo ufw allow 2377
      sudo ufw allow 7946/tcp
      sudo ufw allow 7946/udp
      sudo ufw allow 4789/udp
      sudo ufw allow 8025/tcp
      echo "y" | sudo ufw enable

      # Initialize Swarm with local IP addr manually:
      # sudo docker swarm init --advertise-addr $IP_ADDR
      # Deploy stack to the sward:
      # sudo docker stack deploy -c /vagrant/swarm.yml microservices
    SHELL
  end

  config.vm.define "node2" do |node2|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    node2.vm.box = "generic/ubuntu1804"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # node2.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # node2.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # node2.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # node2.vm.network "private_network", ip: "192.168.33.10"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    node2.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # node2.vm.synced_folder "./scripts", "/vagrant/scripts"

    # Disable the default share of the current code directory. Doing this
    # provides improved isolation between the vagrant box and your host
    # by making sure your Vagrantfile isn't accessible to the vagrant box.
    # If you use this you may want to enable additional shared subfolders as
    # shown above.
    node2.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__args: ["-r", "--exclude=*"]

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    node2.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true

      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end
    #
    # View the documentation for the provider you are using for more
    # information on available options.

    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    node2.vm.provision "shell", inline: <<-SHELL
      export VERSION_CODENAME=$(env -i bash -c '. /etc/os-release; echo $VERSION_CODENAME')
      export IP_ADDR=$(ip addr show eth1 | grep 'inet ' | awk '{print $2}' | cut -f1 -d'/')
      sudo sh -c "echo 'export IP_ADDR=${IP_ADDR}' > /etc/profile.d/ip_addr.sh"
      sudo apt-get install ufw ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      sudo apt-get update
      sudo apt-get install docker.io -y

      cd /vagrant
      sudo hostnamectl set-hostname node2

      # Firewall
      sudo ufw allow ssh
      sudo ufw allow http
      sudo ufw allow https
      sudo ufw allow 2377
      sudo ufw allow 7946/tcp
      sudo ufw allow 7946/udp
      sudo ufw allow 4789/udp
      sudo ufw allow 8025/tcp
      echo "y" | sudo ufw enable

      # Join to Swarm cluster manually
    SHELL
  end
end
